spring:
  output:
    ansi:
      enabled: always
  application:
    name: webflux-coroutine
  r2dbc:
    url: r2dbc:pool:mariadb://127.0.0.1:3306/sample
    username: user
    password: 1234
  sql:
    init:
      mode: always
      schema-locations: classpath:db-init/schema.sql
logging:
  level:
    com.example: debug

---
spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:pool:h2:mem://localhost/sample